# Assignment7

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題1

pandasでDataフォルダの```example.json```を読み込む。

In [ ]:
import pandas as pd

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
file_path = '/content/drive/MyDrive/example.json'
df = pd.read_json(file_path, lines=True)

## 課題2

pandasでDataフォルダの```state-abbrevs.csv```、```state-areas.csv```、```state-population.csv```を読み込む。

これらのデータを使って、**2010年**アメリカの各州の人口密度を計算しよう。

In [24]:
file_path2 = '/content/drive/MyDrive/データ/state-abbrevs.csv'
df2 = pd.read_csv(file_path2)

In [25]:
file_path3 = '/content/drive/MyDrive/データ/state-areas.csv'
df3 = pd.read_csv(file_path3)

In [26]:
file_path4 = '/content/drive/MyDrive/データ/state-population.csv'
df4 = pd.read_csv(file_path4)

In [34]:
merged_df = pd.merge(df2, df3, on='state', how='outer')

final_df = pd.merge(merged_df, df4, left_on='abbreviation', right_on='state/region', how='outer')

In [35]:
final_df

,state,abbreviation,area (sq. mi),state/region,ages,year,population
0,Alaska,AK,656425.0,AK,total,1990.0,553290.0
1,Alaska,AK,656425.0,AK,under18,1990.0,177502.0
2,Alaska,AK,656425.0,AK,total,1992.0,588736.0
3,Alaska,AK,656425.0,AK,under18,1991.0,182180.0
4,Alaska,AK,656425.0,AK,under18,1992.0,184878.0
...,...,...,...,...,...,...,...
2540,Wyoming,WY,97818.0,WY,total,1991.0,459260.0
2541,Wyoming,WY,97818.0,WY,under18,1991.0,136720.0
2542,Wyoming,WY,97818.0,WY,under18,1990.0,136078.0
2543,Wyoming,WY,97818.0,WY,total,1990.0,453690.0
2544,Puerto Rico,NaN,3515.0,NaN,NaN,NaN,NaN

In [41]:
#2010年アメリカの各州の人口密度
df_2010_state = final_df[(final_df['year'] == 2010) & (final_df['ages'] == 'total')]

df_2010_state['population_density'] = df_2010_state['population'] / df_2010_state['area (sq. mi)']

print(df_2010_state[['state', 'population_density']])

                     state  population_density
43                  Alaska            1.087509
51                 Alabama           91.287603
141               Arkansas           54.948667
149                Arizona           56.214497
197             California          228.051342
283               Colorado           48.493718
293            Connecticut          645.600649
341   District of Columbia         8898.897059
427               Delaware          460.445752
475                Florida          286.597129
485                Georgia          163.409902
570                 Hawaii          124.746707
618                   Iowa           54.202751
629                  Idaho           18.794338
714               Illinois          221.687472
725                Indiana          178.197831
773                 Kansas           34.745266
858               Kentucky          107.586994
869              Louisiana           87.676099
954          Massachusetts          621.815538
965               Maryland          466.445797
1050                 Maine           37.509990
1061              Michigan          102.015794
1146             Minnesota           61.078373
1194              Missouri           86.015622
1205           Mississippi           61.321530
1253               Montana            6.736171
1338        North Carolina          177.617157
1349          North Dakota            9.537565
1434              Nebraska           23.654153
1482         New Hampshire          140.799273
1493            New Jersey         1009.253268
1578            New Mexico           16.982737
1589                Nevada           24.448796
1637              New York          356.094135
1722                  Ohio          257.549634
1733              Oklahoma           53.778278
1818                Oregon           39.001565
1829          Pennsylvania          275.966651
1914                   NaN                 NaN
1962          Rhode Island          681.339159
1973        South Carolina          144.854594
2058          South Dakota           10.583512
2069             Tennessee          150.825298
2154                 Texas           93.987655
2203                   NaN                 NaN
2213                  Utah           32.677188
2261              Virginia          187.622273
2346               Vermont           65.085075
2394            Washington           94.557817
2442             Wisconsin           86.851900
2453         West Virginia           76.519582
2501               Wyoming            5.768079

/tmp/ipython-input-41-2267434348.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2010_state['population_density'] = df_2010_state['population'] / df_2010_state['area (sq. mi)']

## 課題3

```state/region```、```ages```と```years```でデータフレームをグループして、各グループで$\frac{population}{area (sq. mi)}$の形で人口密度を計算してください。

In [45]:
df_grouped = final_df.groupby(['state/region', 'ages', 'year'])[['population', 'area (sq. mi)']].sum().reset_index()
df_grouped['population_density'] = df_grouped['population'] / df_grouped['area (sq. mi)']
df_grouped

,state/region,ages,year,population,area (sq. mi),population_density
0,AK,total,1990.0,553290.0,656425.0,0.842884
1,AK,total,1991.0,570193.0,656425.0,0.868634
2,AK,total,1992.0,588736.0,656425.0,0.896882
3,AK,total,1993.0,599434.0,656425.0,0.913180
4,AK,total,1994.0,603308.0,656425.0,0.919081
...,...,...,...,...,...,...
2539,WY,under18,2009.0,134960.0,97818.0,1.379705
2540,WY,under18,2010.0,135351.0,97818.0,1.383702
2541,WY,under18,2011.0,135407.0,97818.0,1.384275
2542,WY,under18,2012.0,136526.0,97818.0,1.395714
2543,WY,under18,2013.0,137679.0,97818.0,1.407502